# Generated by Django 4.0.4 on 2022-05-12 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='S_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='unknown_product', max_length=200)),
                ('s_recieved', models.PositiveIntegerField()),
                ('s_sold', models.PositiveIntegerField()),
                ('s_command', models.PositiveIntegerField()),
                ('s_stock', models.PositiveIntegerField()),
                ('s_user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('s_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.week')),
            ],
        ),
        migrations.CreateModel(
            name='D_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(default='unknown_product', max_length=200)),
                ('d_recieved', models.PositiveIntegerField()),
                ('d_sold', models.PositiveIntegerField()),
                ('d_command', models.PositiveIntegerField()),
                ('d_stock', models.PositiveIntegerField()),
                ('d_user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('d_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.week')),
            ],
        ),
    ]
