# Generated by Django 3.2.5 on 2022-05-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyerO',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.goods'),
        ),
        migrations.AddField(
            model_name='order',
            name='sellerO',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='idG',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.goods'),
        ),
        migrations.AddField(
            model_name='stock',
            name='idU',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
