# Generated by Django 4.0.4 on 2022-05-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='funds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
