# Generated by Django 4.0.4 on 2022-06-03 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='logicP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='path_logic', to=settings.AUTH_USER_MODEL),
        ),
    ]
