# Generated by Django 4.0.4 on 2022-05-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='verifiedT',
            field=models.BooleanField(default=False),
        ),
    ]
