# Generated by Django 3.2.5 on 2022-05-16 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameG', models.CharField(max_length=200)),
                ('durG', models.DurationField()),
                ('idG', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idS', models.BigAutoField(primary_key=True, serialize=False)),
                ('quanS', models.FloatField()),
                ('dateS', models.DateField()),
                ('idG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.goods')),
                ('idU', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idO', models.BigAutoField(primary_key=True, serialize=False)),
                ('quanO', models.FloatField()),
                ('dateO', models.DateField()),
                ('buyerO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to=settings.AUTH_USER_MODEL)),
                ('idG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.goods')),
                ('sellerO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
