# Generated by Django 4.0.4 on 2022-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fixed_cost',
            field=models.FloatField(default=1000),
        ),
    ]
