# Generated by Django 3.2.5 on 2022-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='durG',
            field=models.PositiveIntegerField(),
        ),
    ]
