# Generated by Django 4.0.4 on 2022-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_path_logicp'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='chosenP',
            field=models.BooleanField(default=False),
        ),
    ]
