# Generated by Django 4.0.4 on 2022-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_transaction_verifiedt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='funds',
            field=models.FloatField(default=0),
        ),
    ]
