# Generated by Django 4.0.4 on 2022-05-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_goods_durg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dateS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week'),
        ),
    ]
