# Generated by Django 4.0.4 on 2022-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_goods_order_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
            ],
        ),
    ]
