# Generated by Django 4.0.4 on 2022-05-31 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customuser_maxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='priceTransport',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tran_transporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
