# Generated by Django 3.2.5 on 2022-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220516_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codename',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='durG',
            field=models.PositiveIntegerField(),
        ),
    ]
