# Generated by Django 3.2.5 on 2022-05-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_goods_durg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateO',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.week'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dateS',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.week'),
        ),
    ]
