# Generated by Django 3.2.5 on 2022-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_transaction_pricetransport_transaction_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numT',
            field=models.IntegerField(default=0),
        ),
    ]
