# Generated by Django 4.0.4 on 2022-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codename',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
