# Generated by Django 4.0.4 on 2022-06-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_goods_coefg'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='dateP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week'),
        ),
    ]
