# Generated by Django 4.0.4 on 2022-05-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_order_dateo_alter_stock_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('idT', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quanT', models.FloatField()),
                ('priceT', models.FloatField()),
                ('buyerT', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tran_buyer', to=settings.AUTH_USER_MODEL)),
                ('dateT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week')),
                ('sellerT', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tran_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
