# Generated by Django 3.2.5 on 2022-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_customuser_numt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numT',
            field=models.IntegerField(default=10),
        ),
    ]
