# Generated by Django 3.2.5 on 2022-05-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20220517_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('idT', models.BigAutoField(primary_key=True, serialize=False)),
                ('quanT', models.FloatField()),
                ('priceT', models.FloatField()),
                ('buyerT', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tran_buyer', to=settings.AUTH_USER_MODEL)),
                ('dateT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week')),
                ('goods', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.goods')),
                ('sellerT', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tran_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
