# Generated by Django 4.0.4 on 2022-06-10 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_path_datep'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.FloatField(default=0)),
                ('numT', models.IntegerField(default=0)),
                ('fixed_cost', models.FloatField(default=1000)),
                ('date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
