# Generated by Django 4.0.4 on 2022-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quanO',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='priceT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quanT',
            field=models.FloatField(default=0),
        ),
    ]
