# Generated by Django 4.0.4 on 2022-05-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_order_quano_alter_transaction_pricet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goods',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.goods'),
        ),
    ]
