# Generated by Django 4.0.4 on 2022-06-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_infouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fixed_cost',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='funds',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='numT',
        ),
    ]
