# Generated by Django 4.0.4 on 2022-06-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_customuser_fixed_cost_remove_customuser_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='dateW',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.week'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
