# Generated by Django 3.2.5 on 2022-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_customuser_numt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eff', models.FloatField(default=0)),
                ('sal', models.FloatField(default=0)),
            ],
        ),
    ]
