# Generated by Django 3.2.5 on 2022-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='worker',
            name='idT',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
        ),
    ]
