# Generated by Django 4.0.4 on 2022-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_worker_datew_alter_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='eff',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sal',
            field=models.FloatField(default=100),
        ),
    ]
