# Generated by Django 3.2.5 on 2022-06-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20220607_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='idT',
            new_name='id',
        ),
    ]
