# Generated by Django 4.0.4 on 2022-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_worker_eff_alter_worker_sal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='partialS',
            field=models.FloatField(default=0),
        ),
    ]
