# Generated by Django 4.0.4 on 2022-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_stock_partials'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='maxG',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='minG',
            field=models.FloatField(default=0),
        ),
    ]
