# Generated by Django 3.2.5 on 2022-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20220607_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sal',
            field=models.FloatField(default=5),
        ),
    ]
