# Generated by Django 3.2.5 on 2022-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20220607_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='eff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sal',
            field=models.FloatField(),
        ),
    ]
